site_name: LINUX user
site_url: https://github.com/WonyoungCho/LINUX
site_description: LINUX user
repo_url: https://github.com/WonyoungCho/LINUX/
site_author: Wonyoung Cho

extra_javascript: [docs.js]

pages:
    - Home: 'index.md'
    - Basic command: 'basic_comm.md'
    - Cluster server: 'cluster_conf.md'
    - Manjaro: 'manjaro_conf.md'
    
theme: readthedocs
