site_name: LINUX user
site_url: https://github.com/WonyoungCho/LINUX
site_description: LINUX user
repo_url: https://github.com/WonyoungCho/LINUX/
site_author: Wonyoung Cho

extra_javascript: [docs.js]

pages:
    - Home: 'index.md'
    - Configuration: 'config.md'
    - Hardware : 'hardware.md'
    - Basic command: 'basic_comm.md'
    - Bash script: 'bash.md'
    - Cluster server: 'cluster_conf.md'
    - Login server: 'login_server.md'
    - CentOS: 'centos_conf.md'
    - Manjaro: 'manjaro_conf.md'
    - Ubuntu : 'ubuntu_conf.md'
    - R-Studio:
        - Introduction : 'rstudio_int.md'
        - Packages: 'rstudio_pac.md'
    - Golang:
        - Introduction : 'golang_int.md'
    - Haskell:
        - Instroduction : 'haskell_int.md'

    
theme: readthedocs
